server:
  port: 9090
spring:
  datasource:
    url: jdbc:h2:mem:employeemanagement
    driverClassName: org.h2.Driver
    username: vishalpal
    password: 12345678
  jpa:
    database-platform:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vishalpaldeveloper@gmail.com
    password: vwtxcernnhqkival
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework: DEBUG
    com.gamingService: DEBUG  # TODO change to INFO after coding completion